// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEs6MOHTsb90w-h-zR9fOb_cgxd1NGrHk',
    appId: '1:1050044059013:web:6bd5592fed9ad61d96c8ec',
    messagingSenderId: '1050044059013',
    projectId: 'fir-mwf',
    authDomain: 'fir-mwf.firebaseapp.com',
    storageBucket: 'fir-mwf.appspot.com',
    measurementId: 'G-WJSYSM1898',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYWXpCyfr1CNHcPeRXimx0jgHV_BLqrGo',
    appId: '1:1050044059013:android:418b1e8f4d44f7d996c8ec',
    messagingSenderId: '1050044059013',
    projectId: 'fir-mwf',
    storageBucket: 'fir-mwf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEUqA7CIHsEdDAaw9UM2Pps1IKwE3hO28',
    appId: '1:1050044059013:ios:dd614806466de48096c8ec',
    messagingSenderId: '1050044059013',
    projectId: 'fir-mwf',
    storageBucket: 'fir-mwf.appspot.com',
    iosBundleId: 'com.example.syedaap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEUqA7CIHsEdDAaw9UM2Pps1IKwE3hO28',
    appId: '1:1050044059013:ios:048a4f971d7d7bde96c8ec',
    messagingSenderId: '1050044059013',
    projectId: 'fir-mwf',
    storageBucket: 'fir-mwf.appspot.com',
    iosBundleId: 'com.example.syedaap.RunnerTests',
  );
}
